### PR TITLE
Examples: use python3 consistently

### PR DESCRIPTION
**Pull request by yegorich**

### CODE REVIEW

**Comment by svinota** [comment]
TBH, I would rather use `python` everywhere instead of `python3`, but you can convince me.

**Comment by yegorich** [comment]
There is no such thing as `python` anymore. For example, in Debian Bookworm there is only `python3` binary and no symlink as `python`. At least, this is my experience after Python2 was deprecated.

**Comment by svinota** [comment]
Related: https://peps.python.org/pep-0394/

**Comment by svinota** [comment]
Thanks, merged. Will try to keep it consistent.

**Pull request merged**
