### PR TITLE
ss2: install trigger along pyroute2

### PR DESCRIPTION
**Pull request by cherusk**
Perform immediate cli availability.

### CODE REVIEW

**Comment by svinota** [comment]
To be included in the installation routine, the code must have at least unit and functional testing, so we may be sure that no broken/dysfunctional code is installed. The `DiagSocket` is tested more or less, but the tool is not yet.

Another issue is bureaucratic: the package has dual license while the tool is GPL. It's ok in the git repo, but if we're going to install it, it may affect derivative packages (rpm? deb?) as the GPL is not always the choice for them.

**Comment by cherusk** [comment]
Added functional testing comparing with ss as source of truth.

As to the licensing, not certain how to amend accordingly? Am not clinging to what I've set up. Is adding the snd license enough? Do what is needed if quicker.

**Comment by svinota** [comment]
> not certain how to amend accordingly?

Me neither yet. I'll think a bit and merge then tonight.

**Comment by svinota** [comment]
@cherusk Matthias, I merged the PM, but **please** prepare another one changing the `ss2` header to explicitly state the tool is under dual license GPLv2 or Apache v2 according to the package licenses.

**Comment by svinota** [comment]
@cherusk my mistake, I merged the PM after only a review w/o running the tests.

I was forced to revert the merge. Issues:
1. PEP8 violations
2. The testing doesn't work neither on Python2.7.11, nor on Python 3.6.5, and the latter raises multiple deprecation warnings.

So I have to ask you to prepare the PM again fixing that (please use flake8 to check PEP8) + licensing.

**Comment by cherusk** [comment]
>  1. The testing doesn't work neither on Python2.7.11, nor on Python
>     3.6.5, and the latter raises multiple deprecation warnings.
>
Odd,  all worked for Python 2.7.12, must admit was ignoring PY3.

> So I have to ask you to prepare the PM again fixing that (please use
> flake8 to check PEP8) + licensing.
>
Well, I continuously ran flake etc. via the test framing, only deemed
remaining ones as 'neglible', although am not challenging a stringent
regime.

Will try to cover the defects ...

-- 
Besten Gruß

Matthias Tafelmeier

**Comment by cherusk** [comment]
Towards 2.)

8<------------------------------------------------
kernel: 4.17.19-200.fc28.x86_64
python: /usr/bin/python [Python 2.7.14]
flake8: /usr/bin/flake8 [3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Linux]
nose: /usr/bin/nosetests [nosetests version 1.3.7]
8<------------------------------------------------
test_cli.TestBasic.test_comments_bang ... SKIP: required user root
test_cli.TestBasic.test_comments_hash ... SKIP: required user root
test_cli.TestBasic.test_comments_mixed ... SKIP: required user root
test_cli.TestBasic.test_dump_lo ... ok
test_cli.TestBasic.test_ensure ... SKIP: required user root
test_cli.TestPopen.test_comments_bang ... SKIP: required user root
test_cli.TestPopen.test_comments_hash ... SKIP: required user root
test_cli.TestPopen.test_comments_mixed ... SKIP: required user root
test_cli.TestPopen.test_dump_lo ... ok
test_cli.TestPopen.test_ensure ... SKIP: required user root
**test_cli.TestTools.test_ss2 ... ok**

Even on another PY2 version, see no stumbling blocks. Must admit, was hacking quite into the testing code, but that's down to a preliminarily "brittle" testing framework.

**Comment by cherusk** [comment]
Actually, never ran from the makefile, but in test context directly, along the lines of:

matthias@vm2:~/git/pyroute2/tests$ bash run.sh

**Comment by cherusk** [comment]
Technically, also python3 covered now, before I push:
Well, in my eyes, the Depr.-Warnings are "bearable", mostly for REGEX, what do you think?

8<------------------------------------------------
kernel: 4.17.19-200.fc28.x86_64
python: /usr/bin/python3 [Python 3.6.5]
flake8: /usr/bin/flake8 [3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Linux]
nose: /usr/bin/nosetests [nosetests version 1.3.7]
8<------------------------------------------------
flake8 ... ok
/usr/lib/python3.6/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import find_module, load_module, acquire_lock, release_lock
/media/sf_vm_shared/git/pyroute2/tests/general/test_cli.py:167: DeprecationWarning: invalid escape sequence \.
  ip_v4_addr_sub_re = "([0-9]{1,3}\.){3}[0-9]{1,3}(:\d+)"
/media/sf_vm_shared/git/pyroute2/tests/general/test_cli.py:172: DeprecationWarning: invalid escape sequence \d
  "{1,7}|:))(:\d+)"
/media/sf_vm_shared/git/pyroute2/tests/general/test_cli.py:177: DeprecationWarning: invalid escape sequence \s
  "\s+" + "(?P<dst_ep>" +
test_cli.TestTools.test_ss2 ... ok

**Comment by svinota** [comment]
You may use `r'…'` strings for regexps — that way they do not interfere with the string escaping and there should be no warnings.

**Comment by svinota** [comment]
Pls keep in mind also that your commits from this PR are already in the tree, but are reverted. To correctly merge the change, pls clone the tree again, revert my commit 5d68b16975ec1e4de679e6f439b03beeae724394 , and then add commits that cover the discussed issues.

**Comment by cherusk** [comment]
Continued here: https://github.com/svinota/pyroute2/pull/540

**Pull request merged**
