### PR TITLE
Ss2 unix

### PR DESCRIPTION
**Pull request by cherusk**

### CODE REVIEW

**Comment by cherusk** [comment]
Gosh, branching tactis wasn't brilliant. Anyways, saves the merging effort. ;)

**Comment by cherusk** [comment]
Schema to expect:
    "UNIX": {
        "flows": [
            {
                "usr_ctxt": {
                    "root": {
                        "791": {
                            "full_cmd": [
                                "/usr/bin/abrt-dump-journal-xorg", 
                                "-fxtD"
                            ], 
                            "cmd": "/usr/bin/abrt-dump-journal-xorg", 
                            "fds": [
                                2, 
                                1
                            ]
                        }
                    }
                }, 
                "inode": 21297, 
                "shutdown": 1, 
                "peer_inode": 21298
            }, 
	]
    }
}

**Comment by svinota** [comment]
Please rebase. Thanks for the contribution!

**Comment by cherusk** [comment]
Resolved.

**Comment by svinota** [comment]
```
test_cli.TestTools.test_ss2 ... ERROR

======================================================================
ERROR: test_cli.TestTools.test_ss2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_cli.py", line 290, in test_ss2
    tcp_flows_hive[what] = future.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/peet/Projects/pyroute2/tests/general/test_cli.py", line 245, in do_ss
    refined_flow = parser.parse_flow(flow)
  File "/home/peet/Projects/pyroute2/tests/general/test_cli.py", line 209, in parse_flow
    pid = self.pid_re.search(matter).group('pid')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by cherusk** [comment]
Gosh!

**Comment by cherusk** [comment]
Hold on, went smooth here:

kernel: 4.17.19-200.fc28.x86_64
python: /usr/bin/python [Python 2.7.15]
flake8: /usr/bin/flake8 [3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Linux]
nose: /usr/bin/nosetests [nosetests version 1.3.7]
8<------------------------------------------------
flake8 ... ok
/usr/lib64/python2.7/pkgutil.py:183: ImportWarning: Not importing directory '/usr/lib64/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:183: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
test_cli.TestTools.test_ss2 ... ok

Are you certain youre on latest?

**Comment by svinota** [comment]
Obviously there is something. Let me debug a bit.

**Comment by svinota** [comment]
Sorry for it took quite some time — I couldn't work with the code for some months.

Merged, will be in the nearest release asap.

**Pull request merged**
