### PR TITLE
ss2 - catch further user context instabilities

### PR DESCRIPTION
**Pull request by cherusk**
Move execpton handling further up and catch further perceived exception cases that disturb the user context during forming.

### CODE REVIEW

**Comment by cherusk** [comment]
I cannot comprehend the linter issue. I've already reformatted everything with black linter. :shrug:

**Comment by cherusk** [comment]
Ok, reran black with the parameters from the pre-commit config and it seems to pass. :man_dancing:

**Comment by svinota** [comment]
@cherusk Matthias, will you have also ideas on the CI for the tool — pls ping me

And thanks for the PR

**Comment by cherusk** [comment]
@svinota sorry to ask again, but could you do another minor release again?

**Comment by svinota** [comment]
Yep, will be done asap

**Pull request merged**
