### PR TITLE
WireGuard: add basic support

### PR DESCRIPTION
**Pull request by Vic063**
Add basic support for parser and configuration management

### CODE REVIEW

**Comment by svinota** [comment]
Wow. Thanks, reviewing!

**Comment by svinota** [comment]
Static protocol id fixed — now it uses a dynamic id: https://github.com/svinota/pyroute2/commit/a339667d5e66649dd9b19e6d9e231de75db8af29

Thanks again!

**Comment by pallas** [comment]
It looks like we both added Wireguard support around the same time, although I implemented it as an external project, [wgnlpy](https://github.com/ArgosyLabs/wgnlpy). @Vic063, do you have a roadmap for future work in pyroute2? If so, I'm happy to help out with that, or shift the NLA stuff I used in wgnlpy to use the native support. The interface in wgnlpy does some extra heavy lifting for the user.

**Comment by Vic063** [comment]
Hello @pallas,

nothing planned at the moment on my side.
Feel free to submit what you want.

**Pull request merged**
