### PR TITLE
Fixed unnecessary reloading of libc

### PR DESCRIPTION
**Pull request by hazimeh**
When setns (and other libc functions) are called repeatedly, they load libc at every function call, which results in a lot of I/O overhead.

This fix allows the loaded libc module to be cached globally and fetched later when required.

### CODE REVIEW

**Comment by svinota** [comment]
True. Thanks, merging!

**Comment by ffourcot** [comment]
@svinota usage of ":=" operator will reduce number of python supported version.

It's fine for me, but it's the first usage of this operator in pyroute2 code base.

**Comment by svinota** [comment]
Sure thing, I run tests from 3.6 (see `tox.ini`). In this case it was easier to merge and fix :) Waiting for the CI to finish and pushing the fix.

And @ffourcot  — thanks **a lot** for keeping en eye on the code.

**Comment by svinota** [comment]
updated

**Pull request merged**
