### PR TITLE
ipdb/interfaces: force address load for vlan interfaces

### PR DESCRIPTION
**Pull request by andir**
`vlan` interfaces, like `bond`, `bridge` & `veth` requires a forced address reload

### CODE REVIEW

**Comment by andir** [comment]
I did rebase this onto #312. Tests aren't failing anymore...

**Comment by svinota** [comment]
Merged manually, thanks.

**Comment by andir** [comment]
Do you plan to do a new release soon? I'd like to use this fix in my production env without having to do internal package releases, manually installing a different package etc.. :-)

**Comment by svinota** [comment]
Np. Let's do it on Friday. A good day to break everything :)

**Comment by andir** [comment]
Sounds good to me. Awaiting breakage :+1:

**Comment by svinota** [comment]
@andir — a new tag 0.4.11 is created: https://github.com/svinota/pyroute2/releases/tag/0.4.11

the package is uploaded to pypi: https://pypi.python.org/pypi/pyroute2

**Pull request closed without merging**
