### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
## Description

Hey :wave:, I'm a Developer Outreach at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality and performance improvements](https://deepsource.io/gh/akshgpt7/pyroute2/) to consider.

This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)

## Summary of changes
- Remove unnecessary generator.
- Iterate dictionary directly instead of using `.keys()`.
- Remove calling `len()` for comparison.
- Use literal syntax instead of function calls to create data structure.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

### CODE REVIEW

**Comment by svinota** [comment]
Sounds interesting, though. Let me play a bit with it.

**Comment by akshgpt7** [comment]
@svinota Sure! Let me know if you have any questions, or need any changes to be made.

**Comment by akshgpt7** [comment]
@svinota any updates on this?

**Comment by svinota** [comment]
Yep. Was busy fixing the CI pipeline. Now it's ready, merging.

**Pull request merged**
