### PR TITLE
(WIP) add nfconntrack count support

### PR DESCRIPTION
**Pull request by ffourcot**
Hello,

This patch is a proof of context (not to merge) of nfconntrack count command.

However, this request return only one netlink message, without any "DONE" message. So it's not detected by pyroute2 and hang forever.

I tried to add a "terminate" condition, but it does not work since it skips matching messages. I checked code of conntrack tools, and it uses special code to match this command and get the single message.

### CODE REVIEW

**Comment by svinota** [comment]
Got it, will play with the code tonight.

Thanks!

**Comment by svinota** [comment]
Please look at the `terminate` branch. If it helps, then we may go that way.

**Comment by ffourcot** [comment]
It works for me, thanks. I updated and rebased the commit to use this new feature

**Comment by svinota** [comment]
So I merge all into the master.

**Comment by svinota** [comment]
Merged manually

**Comment by svinota** [comment]
Thanks a lot for the contribution!

**Comment by svinota** [comment]
The `NFCTSocket` class is re-exported from the root module.

From now on one can import it by
```
from pyroute2 import NFCTSocket
```

**Pull request closed without merging**
