### PR TITLE
Portrange

### PR DESCRIPTION
**Pull request by ffourcot**
Should fix all @AZaugg needs, and provide more documentation for future usage. Any comment is welcome.

### CODE REVIEW

**Comment by AZaugg** [comment]
This looks good. Everything I am looking for!

**Comment by svinota** [comment]
Only two comments.

1. To work with the `basestring` type in Python3 one should define it, or import from `pyroute2.common`:
```python
#
# ./pyroute2/ipset.py:248:30: F821 undefined name 'basestring'
#
# to fix:
from pyroute2.common import basestring
```

2. The `test_ipset.TestIPSet.test_port_range_with_proto` fails on my system.

Nevertheless, I would merge that PR and fix all that thereafter.

**Comment by ffourcot** [comment]
@svinota by the way, is the CI broken? I didn't see tests/pep8 run for this merge request.

**Comment by svinota** [comment]
There were some issues with Travis, so the hook was switched off for some time. I plan to setup own hook. If you have any proposals — welcome.

**Pull request merged**
