### PR TITLE
add HT and VHT decode

### PR DESCRIPTION
**Pull request by linuxlizard**
start of architecture to decode the rest of the IEs

I'm using a class IE as a base for the Information Elements' decoded. The IEs will contain a list of named tuples with 'name','value' as fields. The IEs' values can be nested. The values will be grouped according to the IEEE80211-2016 spec.

### CODE REVIEW

**Comment by linuxlizard** [comment]
I watched the Travis CI output. I'll start cleaning up the warnings in nl80211_scan_dump.py

**Comment by svinota** [comment]
Thanks! To be merged asap

**Comment by linuxlizard** [comment]
What would you think about something like the following instead?  It's using an integer -> class map to convert the IE into a specific class instance. Also the decoded value[] is now integer based instead of string.

My eventual goal is to get the scan results as a JSON dump. From a JSON dump, I can create a Flask app that serves the JSON. And ta-da! I have a remote wifi scanner.

```
           def decode(self):
                nla_base.decode(self)

                self.value = {}

                init = offset = self.offset + 4

                ie_class_map = {
                    NL80211_BSS_ELEMENTS_HT_CAPABILITIES : HT_Capabilities,
                    NL80211_BSS_ELEMENTS_HT_OPERATION : HT_Operation,
                    NL80211_BSS_ELEMENTS_EXT_CAPABILITIES : Extended_Capabilities,
                    NL80211_BSS_ELEMENTS_VHT_CAPABILITIES : VHT_Capabilities,
                    NL80211_BSS_ELEMENTS_VHT_OPERATION : VHT_Operation,
                }

                while (offset - init) < (self.length - 4):
                    (msg_type, length) = struct.unpack_from('BB',
                                                            self.data,
                                                            offset)
                    try:
                        cls = ie_class_map[msg_type]
                    except KeyError:
                        pass
                    else:
                        self.value[msg_type] = cls(self.data[offset:offset + length + 1])
                        self.value[msg_type].decode()
                        offset += length + 2

```

**Comment by svinota** [comment]
Looks nice, you're right. So, I'll wait then for the PR and merge.

Thanks!

**Comment by linuxlizard** [comment]
Quick update: still working on this. Been on vacation with family the last week so I'm a little distracted. I have first steps of my JSON output working. I'm worried about breaking previous nl80211 data formats. I'm learning how to use your CI so I can test before adding to the PR.

**Comment by svinota** [comment]
The nl80211 part is not heavily tested, unfortunately, so you may expect surprises there. If so — please don't hesitate to ping me, we can run debugging sessions together after some time planning. Also ping me in case of any questions.

**Comment by linuxlizard** [comment]
Too many merge conflicts with rebase -i so going to create a new PR.

**Pull request closed without merging**
