### PR TITLE
Use socket via composition rather than inheritance

### PR DESCRIPTION
**Pull request by anguslees**
Due to layers of `__getattr__` games, socket.socket isn't particularly
subclass friendly, and GreenSocket (from eventlet) is slightly worse.

This change just gives up on inheritance-for-implementation and
delegates socket methods to an arms-length object.

Note this change sets explicit wrapper methods rather than relying on
`__getattr__` at run-time, since the latter won't support `super().foo`
calls if a subclass has overridden `foo`.

In particular, the new class can still be used in select() and friends
directly due to the fileno() method.

### CODE REVIEW

**Comment by anguslees** [comment]
Relevant eventlet issue: https://github.com/eventlet/eventlet/issues/198

**Comment by svinota** [comment]
The patch provided breaks the continuous integration pipeline on python3:

```
======================================================================
ERROR: Failure: TypeError (method expected 2 arguments, got 3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/nose/failure.py", line 38, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.3/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.3/imp.py", line 175, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.3/imp.py", line 114, in load_source
    _LoadSourceCompatibility(name, pathname, file).load_module(name)
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/peet/Projects/ci/pyroute2/tests/test_tc.py", line 2, in <module>
    from utils import require_user
  File "/home/peet/Projects/ci/pyroute2/tests/utils.py", line 6, in <module>
    from pyroute2.netlink.rtnl.ifinfmsg import compat_create_bridge
  File "/home/peet/Projects/ci/pyroute2/pyroute2/netlink/rtnl/__init__.py", line 42, in <module>
    from pyroute2.netlink.nlsocket import Marshal
  File "/home/peet/Projects/ci/pyroute2/pyroute2/netlink/nlsocket.py", line 817, in <module>
    setattr(SocketWrapper, name, types.MethodType(f, None, SocketWrapper))
TypeError: method expected 2 arguments, got 3
```

Any ideas how to fix in a compatible way, to get it working both on python2 and python3? Since for me the python3 support is required.

**Comment by svinota** [comment]
I created a work branch `eventlet` — https://github.com/svinota/pyroute2/tree/eventlet

Please review the code there, if it fits your tasks, you we should make something with it.

The branch still has issues in some tests, so the code there is not the final version yet.

**Comment by svinota** [comment]
Related issues: #96, #97, #98.

**Comment by anguslees** [comment]
Not specific to this issue, but also related to usage under eventlet: https://github.com/svinota/pyroute2/issues/99

**Pull request merged**
