### PR TITLE
Update join_ibss method in IW

### PR DESCRIPTION
**Pull request by ryan3thompson**
* Correctly handle frequencies (remove +/- 2304)
* Assign center frequencies only for 40/80/160 MHz
* Assign center freq2 for 80P80

### CODE REVIEW

**Comment by svinota** [comment]
Merging, thanks!

**Comment by svinota** [comment]
Oops, I missed  a typo — got it by the tests. Pls notice it:  5ba31311e749a475003502af679e88d53ffe73ba

**Comment by ryan3thompson** [comment]
Oops! Thank you!

**Comment by svinota** [comment]
To run generic IW tests, one can use::
```
$ sudo make test wlevel=ignore module=test_iwutil
```
It allows to catch most generic mistakes.
Tests prerequisites: `nose`, `coverage`, `flake8` modules, + any wireless interface on the host. Tests are non-destructive (yet, still, huh ;)
To use a specific python version::
```
$ sudo make test python=python3 wlevel=ignore module=test_iwutil
```
(`wlevel` parameter's default will be changed to `ignore` soon, since there is almost no python installations that could pass tests with `-W error`)

**Pull request merged**
